name: angular_redux
version: 1.1.2
homepage: https://github.com/ranquild/angular_redux
description: Bindings to use Redux state management with Angular Dart components

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: '>=4.0.0 <6.0.0'
  redux: '>=3.0.0 <5.0.0'

dev_dependencies:
  pedantic: ">=1.8.0+1 <2.0.0"
