name: angular_redux
version: 1.1.0
homepage: https://github.com/ranquild/angular_redux
description: Redux bindings for Dart and Angular apps

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: '>=4.0.0 <6.0.0'
  redux: '>=3.0.0 <5.0.0'

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
  pedantic: ">=1.8.0+1 <2.0.0"
